### ISSUE TITLE
TS2741: Property 'strategies' is missing in type '{ enabled: true; }' but required in type 'PersistOptions'.

### ISSUE THREAD

**Issue by NaturalDevCR** [Seb-L/pinia-plugin-persist#14]
I tried to use it in Vue3 with typescript, but this warning appears... any hints?

**Comment by Seb-L** [comment]
Hi ! Its linked to this issue https://github.com/Seb-L/pinia-plugin-persist/issues/12 
I'm gonna publish a fix soon to add a default strategy when none is specified. The documentation is ahead of this fix, you can add a strategy with a sessionStorage to fix this while the fix is not published.
