### ISSUE TITLE
'"pinia"' has no exported member named 'GettersTree'. 

### ISSUE THREAD

**Issue by jahnli** [Seb-L/pinia-plugin-persist#24]
'"pinia"' has no exported member named 'GettersTree'. Did you mean '_GettersTree'?  1 import { StateTree, GettersTree, PiniaPluginContext } from 'pinia';

**Comment by kossfun** [comment]
I also encountered the same problem  when  `npm run build`

**Comment by Seb-L** [comment]
Should be fixed with the last version
