### ISSUE TITLE
Would you are planning to support vue2.x? 

### ISSUE THREAD

**Issue by benweng** [Seb-L/pinia-plugin-persist#27]
It's unsupported in vue2.x ,right?

**Comment by Seb-L** [comment]
It is supported if you use vue-composition-api, like here: https://seb-l.github.io/pinia-plugin-persist/#vue2

**Comment by benweng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by benweng** [comment]
> It is supported if you use vue-composition-api, like here: https://seb-l.github.io/pinia-plugin-persist/#vue2


it get wrong if this store add attribute 'persist'!
"Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function."
