### ISSUE TITLE
Nuxt 3.7.2 runtime error

### ISSUE THREAD

**Issue by icymonk** [Seb-L/pinia-plugin-persist#68]
- issue
https://github.com/nuxt/nuxt/issues/23163

- error code
https://github.com/prazdevs/pinia-plugin-persistedstate/blob/a6cfb2e559833c1d15d0b67d9077a217be4c8588/packages/nuxt/src/runtime/plugin.ts#L18

- related revision details
https://github.com/nuxt/nuxt/pull/23148

**Comment by dargmuesli** [comment]
If the reason for this is the linked PR, then there is no issue with this library.
